[project]
org-name= "dhananjaya"
version= "0.1.0"

[dependencies]

[platform]
target = "java8"

    [[platform.libraries]]
    artafactId = "mysql-connector-java"
    version = "8.0.17"
    path = "./mysql-connector-java-8.0.17.jar"
    groupId = "mysql"
    modules = ["test_mod"]
